name:                fileStructure
version:             0.1.0.0
github:              "ogata-k/fileStructure"
license:             BSD3
author:              "ogata"
maintainer:          "ogtkzk@yahoo.co.jp"
copyright:           "(c) ogata"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ogata-k/fileStructure#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-declarative

library:
  source-dirs: src

executables:
  fileStructure:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fileStructure

tests:
  fileStructure:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fileStructure
